name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
  pull_request:
    paths:
      - Dockerfile
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Login to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Get Previous Commit
      id: get_previous_commit
      run: echo "::set-output name=previous_commit::$(git rev-parse HEAD^1)"

    - name: Tag and Push Previous Commit
      run: |
        docker pull benedicthu/nginx-quictls:latest
        docker tag benedicthu/nginx-quictls:latest benedicthu/nginx-quictls:${{ steps.get_previous_commit.outputs.previous_commit }}
        docker push benedicthu/nginx-quictls:${{ steps.get_previous_commit.outputs.previous_commit }}

    - name: Build and Push Multi-Platform Docker Image
      run: docker buildx create --use && docker buildx build --platform linux/amd64,linux/arm64 -t benedicthu/nginx-quictls:latest --push
