name: ci

on:
  push:
    branches:
      - "main"
    paths:
      - Dockerfile

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        if: ${{ github.event_name != 'pull_request' }}
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Tag and Push Previous Commit
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/nginx-quictls:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/nginx-quictls:latest ${{ secrets.DOCKER_USERNAME }}/nginx-quictls:${{ steps.get_previous_commit.outputs.previous_commit }}
          docker image rm ${{ secrets.DOCKER_USERNAME }}/nginx-quictls:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx-quictls:${{ steps.get_previous_commit.outputs.previous_commit }}
      - name: Build and push
        uses: docker/build-push-action@v5
        if: ${{ github.event_name != 'pull_request' }}
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nginx-quictls:latest
          build-args: |
            "BUILD=${{ github.sha }}"