name: NGINX-QuicTLS (all builds)

on:
  push:
    branches:
      - latest
    paths:
      - Dockerfile
      - Dockerfile.without-modsec
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  DOCKER_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-quictls
  GHCR_IMAGE: ghcr.io/${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build-file:
          - { file: Dockerfile, suffix: "" }
          - { file: Dockerfile.without-modsec, suffix: "-without_modsec" }
        platform:
          - linux/amd64
          - linux/arm64
          - linux/arm/v7
          - linux/arm/v6

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_IMAGE }}
            ${{ env.GHCR_IMAGE }}
          tags: |
            type=raw,value=latest${{ matrix.build-file.suffix }},priority=1000
            type=ref,event=branch,suffix=${{ matrix.build-file.suffix }}
            type=ref,event=tag,suffix=${{ matrix.build-file.suffix }}
            type=sha,suffix=${{ matrix.build-file.suffix }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ${{ matrix.build-file.file }}
          platforms: ${{ join(matrix.platform, ',') }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD=${{ github.sha }}-${{ steps.meta.outputs.version }}

      - name: Inspect pushed images
        run: |
          docker buildx imagetools inspect ${{ env.DOCKER_IMAGE }}:latest${{ matrix.build-file.suffix }}
          docker buildx imagetools inspect ${{ env.GHCR_IMAGE }}:latest${{ matrix.build-file.suffix }}
