name: NGINX-QuicTLS (Update versions)

on:
  push:
    branches:
      - dev
    paths:
      - Dockerfile
      - Dockerfile.without-modsec
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dep:
          - { name: "NGINX Mainline", var: "NGX_MAINLINE_VER", repo: "https://github.com/nginx/nginx.git", filter: "release-" }
          - { name: "ModSecurity", var: "MODSEC_VER", repo: "https://github.com/owasp-modsecurity/ModSecurity.git" }
          - { name: "QuicTLS", var: "QUICTLS_VER", repo: "https://github.com/quictls/openssl.git", branch: "openssl-*.*.*+quic" }
          - { name: "Headers More Module", var: "NGX_HEADERS_MORE", repo: "https://github.com/openresty/headers-more-nginx-module.git" }
          - { name: "NJS Module", var: "NGX_NJS", repo: "https://github.com/nginx/njs.git" }
          - { name: "NGX ModSecurity Module", var: "NGX_MODSEC", repo: "https://github.com/SpiderLabs/ModSecurity-nginx.git" }
          - { name: "GeoIP2 Module", var: "NGX_GEOIP2", repo: "https://github.com/leev/ngx_http_geoip2_module.git" }
          - { name: "TLS Dyn Size Module", var: "NGX_TLS_DYN_SIZE", repo: "https://github.com/nginx-modules/ngx_http_tls_dyn_size.git" }

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest version
        id: getver
        run: |
          VER=""
          if [ "${{ matrix.dep.var || '' }}" == "NGX_TLS_DYN_SIZE" ]; then
            git clone https://github.com/nginx-modules/ngx_http_tls_dyn_size ngx_http_tls_dyn_size
            VER=$(ls ngx_http_tls_dyn_size/nginx__dynamic_tls_records_*.patch \
              | sed "s|ngx_http_tls_dyn_size/nginx__dynamic_tls_records_\([0-9.]\+\)+.patch|\1|g" \
              | sort -V \
              | grep -v rc \
              | tail -1)
            rm -rf ngx_http_tls_dyn_size
          elif [ "${{ matrix.dep.branch || '' }}" == "main" ]; then
            VER=$(git ls-remote "${{ matrix.dep.repo }}" refs/heads/main | awk '{print $1}')
          elif [ -n "${{ matrix.dep.branch || '' }}" ]; then
            VER=$(git ls-remote --heads "${{ matrix.dep.repo }}" "${{ matrix.dep.branch }}" \
              | awk -F'/' '{print $3}' | sort -V | tail -1)
          else
            VER=$(git ls-remote --refs --tags "${{ matrix.dep.repo }}" \
              | grep -v '\^{}' \
              | awk -F'/' '{print $3}' \
              | sed "s/^${{ matrix.dep.filter || '' }}//" \
              | sort -V \
              | tail -1)
          fi
          
          if [ -z "$VER" ]; then
            echo "Error: Could not determine version for ${{ matrix.dep.name }}"
            exit 1
          fi

          echo "VER=$VER" >> $GITHUB_OUTPUT
          sed -i "s|ARG ${{ matrix.dep.var }}=.*|ARG ${{ matrix.dep.var }}=${VER}|g" Dockerfile
          sed -i "s|ARG ${{ matrix.dep.var }}=.*|ARG ${{ matrix.dep.var }}=${VER}|g" Dockerfile.without-modsec || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          signoff: true
          delete-branch: true
          commit-message: Update ${{ matrix.dep.name }} to ${{ steps.getver.outputs.VER }}
          title: Update ${{ matrix.dep.name }} to ${{ steps.getver.outputs.VER }}
          body: Update ${{ matrix.dep.name }} to ${{ steps.getver.outputs.VER }}
          branch: update-version-${{ matrix.dep.var }}-${{ steps.getver.outputs.VER }}
          base: dev
          labels: dependencies